version: '2'

volumes:
  portus-registry:


services:
  portus-web:
    container_name: portus-web
    build: .
    command: puma -b tcp://0.0.0.0:3000 -w 3
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${EXTERNAL_IP}
      - PORTUS_DB_HOST=db
      - PORTUS_DB_PASSWORD=portus
    volumes:
      - .:/portus
    ports:
      - 3000:3000
  
  portus-cron:
    container_name: portus-cron
    image: portus-web
    entrypoint: bin/crono
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${EXTERNAL_IP}
      - PORTUS_DB_HOST=db
      - PORTUS_DB_PASSWORD=portus
    volumes:
      - .:/portus
  
  portus-database:
    container_name: portus-database
    image: library/mariadb:10.0.23
    environment:
      MYSQL_ROOT_PASSWORD: portus
  
  registry:
    container_name: portus-registry
    image: library/registry:2.3.1
    environment:
      - REGISTRY_AUTH_TOKEN_REALM=http://${EXTERNAL_IP}:3000/v2/token
      - REGISTRY_AUTH_TOKEN_SERVICE=${EXTERNAL_IP}:${REGISTRY_PORT}
      - REGISTRY_AUTH_TOKEN_ISSUER=${EXTERNAL_IP}
    volumes:
      - portus-registry:/registry_data
      - ./compose/registry/portus.crt:/etc/docker/registry/portus.crt:ro
      - ./compose/registry/config.yml:/etc/docker/registry/config.yml:ro
    ports:
      - ${REGISTRY_PORT}:5000
      - 5001:5001 # required to access debug service
